tab-mode: "apt" # apt, pacman

overwrite:
 # loaders: [bukkit, spigot, paper]
 # version: 1.21.10

search:
  mode: "full" # fast, full
  max-results: 20
  reversed-list: true
  show-incompatible: false

install:
  default-flag: latest # latest, rolling | not recommended: release, beta, alpha
  required-dependencies: true
  optional-dependencies: false

update:
  check-on-startup: true
  install-on-shutdown: false

cache:
  plugins: true
  metadata: true
  tmp-versions: true
