name: Plug-Get
version: '1.0'
main: me.pinkcandy.plugGet.PlugGet
api-version: '1.21'
load: STARTUP
commands:
  plugget:
    usage: /plugget
    aliases: [pg, plug-get]
    permission: plugget.use
    permission-message: "§c"

permissions:
  plugget.use:
    description: ""
    default: op































































































































































































































































































































































































































































































































































































































































































































































































    