name: Plug-Get
version: '1.0'
main: me.pinkcandy.plugGet.PlugGet
api-version: '1.21'
load: STARTUP
folia-supported: true
commands:
  plugget:
    usage: /plugget
    aliases: [pg, plug-get]
    permission: plugget.use
    permission-message: "You do not have permission to use this command."

permissions:
  plugget.use:
    description: "Allows the player to use the /plugget command."
    default: op































































































































































































































































































































































































































































































































































































































































































































































































    